#include "CanvasInterface.h"
#include "Components.h"
#include "Logger.h"
#include "ProjectManager.h"
#include <Xm/MessageB.h>
#include <Xm/Xm.h>
#include <Xm/XmStrDefs.h>
#include <algorithm>
#include <cctype>
#include <cstddef>
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <sstream>

static Widget GetShellParent(Widget w) {
    while (w != NULL && !XtIsShell(w))
        w = XtParent(w);
    return w;
}

void ProjectManager::SaveIndividualHeaderFile(Widget parent, std::string pathToSave, std::string className) {
    std::vector<CanvasInterface::EditorWidgetInstance> widgets = g_canvas->GetWidgetList();
    std::stringstream ss; // File buffer
    ss  << "// Generated header file: " << className << ".h \n"
        << "// Generated by MotifDesigner version " << PROJECT_VERSION_STR << "\n"
        << "#include <Xm/Xm.h>\n"
        << "#include <Xm/Form.h>\n"
        << "#include <Xm/PushB.h>\n"
        << "#include <Xm/Label.h>\n"
        << "#include <Xm/TextF.h>\n"
        << "#include <Xm/ToggleB.h>\n"
        << "#include <Xm/Frame.h>\n"
        << "#include <Xm/DrawingA.h>\n"
        << "#include <iostream>\n\n";
    
    std::string guard = className;
    std::transform(guard.begin(), guard.end(), guard.begin(), ::toupper);

    ss  << "#ifndef " << guard << "_H\n"
        << "#define " << guard << "_H\n\n";
    
    ss << "class " << className << " {\n"
        << "    public:\n";
    
    for (auto& widget : widgets) {
        std::string widgetName = widget.name;
        ss << "        Widget " << widgetName << ";\n";
    }

    ss  << "        Widget BuildUserInterface(Widget parent) {\n"
        << "            Arg args[32];\n"
        << "            int n;\n"
        << "            Widget FormParent = XmCreateForm(parent, (char*)\"FormParent\", NULL, 0);\n";
    
    for (auto& widget : widgets) {
    ss  << "            n = 0;\n";
    ss  << "            XtSetArg(args[n], XmNx, " << widget.x << "); n++;\n";
    ss  << "            XtSetArg(args[n], XmNy, " << widget.y << "); n++;\n";
    ss  << "            XtSetArg(args[n], XmNwidth, " << widget.width << "); n++;\n";
    ss  << "            XtSetArg(args[n], XmNheight, " << widget.height << "); n++;\n";
    switch (widget.type) {
        case CanvasInterface::ToolTypes::Button:
            ss  << "            XtSetArg(args[n], XmNlabelString, XmStringCreateLocalized((char*)\"" << widget.value << "\"));\n";
            ss  << "            " << widget.name << " = XmCreatePushButton(FormParent, (char*)\"" << widget.name << "\", args, n);\n";
            break;
        case CanvasInterface::ToolTypes::Label:
            ss  << "            XtSetArg(args[n], XmNlabelString, XmStringCreateLocalized((char*)\"" << widget.value << "\"));\n";
            ss  << "            " << widget.name << " = XmCreateLabel(FormParent, (char*)\"" << widget.name << "\", args, n);\n";
            break;
        case CanvasInterface::ToolTypes::TextField:
            ss  << "            XtSetArg(args[n], XmNvalue, (char*)\"" << widget.value << "\");\n";
            ss  << "            " << widget.name << " = XmCreateTextField(FormParent, (char*)\"" << widget.name << "\", args, n);\n";
            break;
        case CanvasInterface::ToolTypes::Toggle:
            ss  << "            XtSetArg(args[n], XmNlabelString, XmStringCreateLocalized((char*)\"" << widget.value << "\"));\n";
            ss  << "            " << widget.name << " = XmCreateToggleButton(FormParent, (char*)\"" << widget.name << "\", args, n);\n";
            break;
        case CanvasInterface::ToolTypes::Frame:
            ss  << "            " << widget.name << " = XmCreateFrame(FormParent, (char*)\"" << widget.name << "\", args, n);\n";
            break;
        default:
            break;
    }
    ss  << "            XtManageChild(" << widget.name << ");\n\n";
    }
    ss  << "            return FormParent;\n";
    ss  << "        }\n";
    ss  << "};\n";
    ss  << "#endif\n";
    // Save in pathToSave/className.h
    std::ofstream headerFile(pathToSave + "/" + className + ".hpp", std::ios::out | std::ios::binary);
    if (!headerFile.is_open()) {
        Widget shellParent = GetShellParent(parent);
        Arg args[1];
        XtSetArg(args[0], XmNmessageString, XmStringCreateLocalized((char*)"Failed to save header file!"));
        Widget errorDialog = XmCreateErrorDialog(shellParent, (char*)"ErrorDialog", args, 1);
        Widget helpButton = XmMessageBoxGetChild(errorDialog, XmDIALOG_HELP_BUTTON);
        XtUnmanageChild(helpButton);
        XtManageChild(errorDialog);
        Logger::log("[FAIL] opening file failed");
        return;
    }
    headerFile << ss.str();
    headerFile.close();
    Logger::log("[SUCCESS] saving header file");
    if (parent != NULL) {  
        Widget shellParent = GetShellParent(parent);
        Logger::log(shellParent ? "OK, shell parent found, showing dialog" : "WARNING: no shell parent found"); 
        if (shellParent == NULL) shellParent = parent; // fallback
        Arg args[1];
        XtSetArg(args[0], XmNmessageString, XmStringCreateLocalized((char*)(std::string("Header file saved successfully to ") + pathToSave + "/" + className + ".hpp").c_str()));
        Widget successDialog = XmCreateInformationDialog(shellParent, (char*)"InformationDialog", args, 1);
        Widget helpButton = XmMessageBoxGetChild(successDialog, XmDIALOG_HELP_BUTTON);
        XtUnmanageChild(helpButton);
        XtManageChild(successDialog);
    } else {
        Logger::log("OK, parent is null, NOT showing dialog");
        return;
    }    
    StatusBar::UpdateStatusBar((std::string("Header file saved in: ") + pathToSave + "/" + className + ".hpp").c_str());
}